apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: site
resources:
  - resources.yaml
  - networkpolicy.yaml
replicas:
  - name: site
    count: 2
images:
  - name: hashbang/hashbang.sh
    digest: sha256:2d931005383de01daf6f4933be9e7c17a1d8832dc46d11492c79d9067d40a99b
