apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ircd
resources:
  - certificate.yaml
  - resources.yaml
configMapGenerator:
- name: irc-config
  options:
    disableNameSuffixHash: true
  files:
  - files/ircd.motd
  - files/ircd.yaml
images:
  - name: oragono/oragono:latest
    # v2.5.0:
    digest: sha256:986b99c9a7171d0bdbe050520a027dc2b361d523d00b7007ec8aef55c583cfc9
