apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/coreos/kube-prometheus?ref=de2d1b523135cd4e561b899b294f015e52e4f704 # Random master commit that supports Kubernetes 1.19
  - ingress.yaml
  - cilium-service-monitor.yaml
  - ./loki
  - ./promtail
  - prometheus-additional-targets.yaml
  - grafana-role.yaml
patches:
  - container-images.patch.yaml
  - cluster-wide.patch.yaml
  - grafana-auth.patch.yaml
  - grafana-sidecar.patch.yaml
  - prometheus-additional-scrape-configs.patch.yaml
  - prometheus-persistent-volume.patch.yaml
patchesJson6902:
  - target:
      version: v1
      kind: Service
      namespace: monitoring
      name: grafana
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 80
  # Workaround https://github.com/coreos/kube-prometheus/issues/586
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: alertmanagers.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: podmonitors.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: prometheusrules.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: servicemonitors.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: thanosrulers.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
configMapGenerator:
  - name: grafana-dashboard-cilium
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      # https://github.com/cilium/cilium/tree/6fe8d092a6796d36230a0e3480cd2a8472e1a6f0/examples/kubernetes/addons/prometheus/files/grafana-config
      - files/grafana-dashboard-cilium.json
      - files/grafana-dashboard-cilium-operator.json
  - name: grafana-dashboard-ingress-nginx
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      # https://github.com/kubernetes/ingress-nginx/blob/810acfafbef86d9dc05e0ece68c97d0c93344632/deploy/grafana/dashboards/nginx.json
      - files/grafana-dashboard-ingress-nginx.json
  - name: grafana-dashboard-shell-nodes
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      # modified from https://raw.githubusercontent.com/grafana/kubernetes-app/master/src/dashboards/k8s-node.json
      - files/grafana-dashboard-shell-nodes.json
secretGenerator:
  - name: grafana-datasources
    namespace: monitoring
    behavior: merge
    options:
      disableNameSuffixHash: true
    files:
      - files/datasource-loki.yaml
generators:
  - secret-generator.yaml
images:
  - name: grafana/grafana:7.3.7
    digest: sha256:f140fde5ba622745926b1e390b6ff335c1a0b7a1126cd4211600534f922ef4c0
  - name: kiwigrid/k8s-sidecar:0.1.178
    digest: sha256:95feeef7afb892cb781fe67d5d487a087049386888b1f7e84a2c4a63c2f09259
  - name: directxman12/k8s-prometheus-adapter:v0.8.3
    digest: sha256:4aab584153e7cd9caad64ec6c3e7ab7750c99f60aa042bf31cd440a397407cb7
  - name: quay.io/brancz/kube-rbac-proxy:v0.8.0
    digest: sha256:05e15e1164fd7ac85f5702b3f87ef548f4e00de3a79e6c4a6a34c92035497a9a
  - name: quay.io/coreos/kube-state-metrics:v1.9.7
    digest: sha256:2f82f0da199c60a7699c43c63a295c44e673242de0b7ee1b17c2d5a23bec34cb
  - name: quay.io/prometheus-operator/prometheus-operator:v0.45.0
    digest: sha256:59b431d69a023d5baa44e868cc5c8f04ab4e5b045ca5b10dbd5a9dc9d67b7868
  - name: quay.io/prometheus/node-exporter:v1.1.0
    digest: sha256:8f9dc6bafcb1d10e1b1de65491465797bd0d264175e5a1131f83ad873cf54064
  - name: quay.io/prometheus/blackbox-exporter:v0.18.0
    digest: sha256:83e57545859abeb5ebfb878b2ca12bba7155279bec704fdf160b6e913f967257
  - name: jimmidyson/configmap-reload:v0.5.0
    digest: sha256:91467ba755a0c41199a63fe80a2c321c06edc4d3affb4f0ab6b3d20a49ed88d1
