apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  # v1.7.6
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=b04c25eca8f1660359e325acd4be5338719e59a0
  - ingress.yaml
  - argo-cd-service-monitor.yaml
  - argocd-notifications/
  # Projects
  - projects/default.yaml
  # Applications to deploy
  - applications/argocd.yaml
  - applications/book.yaml
  - applications/cert-manager.yaml
  - applications/cert-manager-issuers.yaml
  - applications/external-dns.yaml
  - applications/ingress-nginx.yaml
  - applications/ircd.yaml
  - applications/matterbridge.yaml
  - applications/monitoring.yaml
  - applications/mtls.yaml
  - applications/site.yaml
  - applications/userdb-api.yaml
  - applications/webirc.yaml
patches:
  - argo-cd-repo-server-ksops.patch.yaml
  - argo-cd-allow-alpha-plugins.patch.yaml
  - argo-cd-import-pgp-key.patch.yaml
  - argo-cd-repository-credentials.patch.yaml
  - argo-cd-rbac.patch.yaml
  - argo-cd-allow-status-badges.patch.yaml
  - users.patch.yaml
configMapGenerator:
  - name: grafana-dashboard
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      # From https://github.com/argoproj/argo-cd/blob/master/examples/dashboard.json
      - files/grafana-dashboard-argocd.json
      # From https://argoproj-labs.github.io/argocd-notifications/grafana-dashboard.json
      - files/grafana-dashboard-argocd-notifications.json
  - name: argocd-gpg-keys-cm
    behavior: merge
    options:
      disableNameSuffixHash: true
    files:
      - gpg-keys/C91A9911192C187A
      - gpg-keys/6785F7AF28DE7081
      - gpg-keys/E90A401336C8AAA9
      - gpg-keys/68907D8BCCD85A5A
      - gpg-keys/B10116B8193F2DBD
      - gpg-keys/26CDD32189AA2885
images:
  - name: argoproj/argocd:v1.7.6
    digest: sha256:e561b4caa56a7ec41f59ba305b1f8158ada2c7eaee7a87d29fad8d88da650fec
  - name: quay.io/dexidp/dex:v2.22.0
    digest: sha256:01e996b4b60edcc5cc042227c6965dd63ba68764c25d86b481b0d65f6e4da308
  - name: redis:5.0.8
    digest: sha256:de935cb5eb1d96a5b75c871cd408a728b89d100712ae4599eb994bb7a41a9336
  - name: viaductoss/ksops:v2.1.4
    digest: sha256:f1f5b7e2ee32f7b2a2668f4cc3ee9051ed51277ee336a2f842568cf2759890c1
generators:
  - secret-generator.yaml
replicas:
- name: argocd-server
  count: 3
