apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
- resources.yaml
- networkpolicy.yaml
- service-monitor.yaml
patches:
- aws_credentials.yaml
generators:
- secret-generator.yaml
images:
- name: external-dns
  newName: eu.gcr.io/k8s-artifacts-prod/external-dns/external-dns:v0.7.3
  digest: sha256:221454cbba7aa159097e89751c3b461de84a23f652450e645d97e29190c5d5de
