apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
- resources.yaml
- networkpolicy.yaml
- service-monitor.yaml
patches:
- aws_credentials.yaml
generators:
- secret-generator.yaml
images:
- name: external-dns
  newName: eu.gcr.io/k8s-artifacts-prod/external-dns/external-dns:v0.7.5
  digest: sha256:ec0b0f8fe353f827511e3e74493e2b77f5ba5def83baf403f9e36ef7dfd7f5f6
